### PR TITLE
:art: Fix layout (#1050)

### LINKED ISSUE #1050: トップページ: 小さい画面の時に余白が大きすぎるのでやや狭くしましょう

### PR DESCRIPTION
**Pull request by KATO-Hiro**
close #1050

## Summary by CodeRabbit

- **New Features**
	- Enhanced responsiveness of the layout for better viewing on various screen sizes.

- **Bug Fixes**
	- Improved readability of headings on mobile devices by adjusting font size.

- **Style**
	- Refined button layout to full-width for improved usability on smaller screens.
	- Streamlined content organization with consistent padding and margin adjustments.

- **Chores**
	- Retained comments for potential future improvements, indicating ongoing development efforts.

### CODE REVIEW

File: src/routes/+page.svelte [hunk 1]
```diff
@@ -27,73 +27,81 @@
...
+        controls
+        loop
+      />
+    </div>
 
-  <!-- FIXME: キャッチコピーを改善 -->
-  <Heading tag="h2" class="mt-36 mb-3" customSize="text-xl font-medium  md:text-2xl lg:text-3xl">
-    (開発中) 問題集で得意を伸ばす・苦手を克服
-  </Heading>
+    <!-- FIXME: キャッチコピーを改善 -->
```
Comment (KATO-Hiro) [inline src/routes/+page.svelte]: 古いコメントは消しておきましょう

Comment (KATO-Hiro) [reply src/routes/+page.svelte]: 削除しました
