### PR TITLE
:art: Fix colors and styles (#1133)

### LINKED ISSUE #1133: ダークモードの配色を修正しましょう

### PR DESCRIPTION
**Pull request by KATO-Hiro**
close #1133

## Summary by CodeRabbit

- **New Features**
	- Introduced responsive text size adjustments for links on extra-small screens.
	- Replaced standard anchor elements with a dedicated `ExternalLinkWrapper` component for better external link handling in task lists.

- **Style**
	- Updated text color in dark mode for various components to enhance visual consistency.
	- Modified background color values for a refreshed design palette throughout the application.

### CODE REVIEW

File: src/lib/components/ExternalLinkWrapper.svelte [hunk 1]
```diff
@@ -5,7 +5,7 @@
 
 <a
   href={url}
```
Comment (KATO-Hiro) [inline src/lib/components/ExternalLinkWrapper.svelte:9]: Aboutページなどにも影響しているのでrevertした方が良さそうです。

Comment (KATO-Hiro) [reply src/lib/components/ExternalLinkWrapper.svelte:9]: オプションで変更できるようにしました。
